#:schema node_modules/wrangler/config-schema.json
name = "vitest-pool-esm-bug"
main = "src/index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

[[services]]
binding = "PING_SERVICE"
service = "vitest-pool-esm-bug"
entrypoint = "PingService"

[[services]]
binding = "AUTHENTICATED_USER_SERVICE"
service = "vitest-pool-esm-bug"
entrypoint = "AuthenticatedUserService"
